framework:
  default_locale: "%app.default_locale%"
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks:
      - "%app.default_locale%"
#        providers:
#            crowdin:
#                dsn: '%env(resolve:CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(resolve:LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(resolve:LOKALISE_DSN)%'
